/**
 * Generates lib/map-dots.generated.ts: the hero globe's land dots.
 *
 *   npm run generate:map
 *
 * Source: Natural Earth 1:110m land, lakes and countries (public domain),
 * pinned to a release. We sample a regular grid in *screen* space (so dots
 * are evenly spaced on the globe image), unproject each point, and keep it
 * if it is on land. Output is two SVG path strings ("M x y h0" segments,
 * drawn with round caps), so ~1.9k dots cost two DOM nodes.
 */
import { writeFileSync } from "node:fs";
import { CENTER, RADIUS, VIEW, unproject } from "../lib/map-projection.ts";

const SOURCE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson";
const STEP = 10; // grid spacing in viewBox units
const OUT = new URL("../lib/map-dots.generated.ts", import.meta.url);

type Ring = [number, number][];
type Polygon = Ring[]; // outer ring + holes
type Geometry =
  { type: "Polygon"; coordinates: Polygon } | { type: "MultiPolygon"; coordinates: Polygon[] };
type Feature = { properties: Record<string, unknown>; geometry: Geometry };

async function load(name: string): Promise<Feature[]> {
  const res = await fetch(`${SOURCE}/${name}.geojson`);
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  return ((await res.json()) as { features: Feature[] }).features;
}

const polygons = (features: Feature[]): Polygon[] =>
  features.flatMap((f) =>
    f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates,
  );

function inRing(lon: number, lat: number, ring: Ring): boolean {
  let hit = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) hit = !hit;
  }
  return hit;
}

const inPolygon = (lon: number, lat: number, [outer, ...holes]: Polygon) =>
  inRing(lon, lat, outer) && !holes.some((h) => inRing(lon, lat, h));

const [land, lakes, countries] = await Promise.all([
  load("ne_110m_land"),
  load("ne_110m_lakes"),
  load("ne_110m_admin_0_countries"),
]);
const landPolys = polygons(land);
const lakePolys = polygons(lakes);
const syriaPolys = polygons(countries.filter((f) => f.properties.ADM0_A3 === "SYR"));
if (!syriaPolys.length) throw new Error("Syria not found in countries data");

let landPath = "";
let syriaPath = "";
let count = 0;
for (let y = STEP / 2; y < VIEW; y += STEP) {
  for (let x = STEP / 2; x < VIEW; x += STEP) {
    if (Math.hypot(x - CENTER, y - CENTER) > RADIUS - STEP / 3) continue;
    const ll = unproject(x, y);
    if (!ll) continue;
    const [lon, lat] = ll;
    if (!landPolys.some((p) => inPolygon(lon, lat, p))) continue;
    if (lakePolys.some((p) => inPolygon(lon, lat, p))) continue;
    const seg = `M${x} ${y}h0`;
    if (syriaPolys.some((p) => inPolygon(lon, lat, p))) syriaPath += seg;
    else landPath += seg;
    count++;
  }
}

writeFileSync(
  OUT,
  `// Generated by scripts/generate-map-dots.mts — do not edit by hand.
// Natural Earth 1:110m (public domain), orthographic globe centered on Syria.
// ${count} dots on a ${STEP}-unit grid in a ${VIEW}×${VIEW} viewBox.

export const LAND_DOTS =
  "${landPath}";

export const SYRIA_DOTS =
  "${syriaPath}";
`,
);
console.log(`Wrote ${count} dots (${(landPath.length + syriaPath.length) / 1000} KB of path data)`);
